fonte:
  nome: Rubik-Regular.ttf
  color: '#b4963c'
formatos:
  1200x768:
    # PERCENTUAL %
    top_pos: 65  
    bottom_pos: 15
    left_pos: 15 
    right_pos: 15
    # PIXEL
    font_size: 68
    line_thikness: 5
    line_space: 35
  400x400:
    # PERCENTUAL %
    top_pos: 65  
    bottom_pos: 15
    left_pos: 15 
    right_pos: 15
    # PIXEL
    font_size: 26
    line_thikness: 3
    line_space: 15
  300x580:
    # PERCENTUAL %
    top_pos: 75  
    bottom_pos: 15
    left_pos: 15 
    right_pos: 10
    # PIXEL
    font_size: 30
    line_thikness: 2
    line_space: 12
  circulo:
    # PERCENTUAL %
    top_pos: 65  
    bottom_pos: 20
    left_pos: 18  
    right_pos: 18 
    # PIXEL
    font_size: 30
    line_thikness: 0
    line_space: 30
